# Generated by Django 3.0.4 on 2020-03-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='title of donor.', max_length=120)),
                ('email', models.CharField(max_length=255)),
                ('blood', models.CharField(max_length=2)),
            ],
        ),
    ]
